name: Deploy Doxygen Docs
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build-doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get install -y doxygen meson ninja-build
      - name: Meson setup
        run: |
          meson setup builddir -Ddoc=enabled
      - name: Build Doxygen docs
        run: |
          ninja -C builddir doc/html
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: builddir/doc/html
  deploy:
    needs: build-doxygen
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
