name: build and run tests
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        compiler: [gcc, clang, msvc]
        os: [ubuntu-latest, windows-latest]
        exclude:
          - os: ubuntu-latest
            compiler: msvc
          - os: windows-latest
            compiler: gcc
          - os: windows-latest
            compiler: clang
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Meson and Ninja
        run: |
          python -m pip install meson ninja
      - name: Set up compiler environment
        if: matrix.compiler != 'msvc'
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.compiler }}
        shell: bash
      - name: Set up MSVC environment
        if: matrix.compiler == 'msvc'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: Setup meson
        run: |
          meson setup builddir --buildtype=debug -Dwerror=true -Dtools=enabled
        env:
          CC: ${{ matrix.compiler == 'gcc' && 'gcc' || matrix.compiler == 'clang' && 'clang' || 'cl' }}
      - name: Configure sanitizer
        if: matrix.compiler == 'gcc'
        run: |
          meson configure builddir -Db_sanitize=address,undefined
      - name: Run tests
        run: |
          ninja test -v -C builddir
